### ISSUE TITLE
iCloud storage integration instead of local storage.

### ISSUE THREAD

**Issue by jhaleit** [xibbon/XogotIssues#11]
It would be amazing if we can have iCloud storage instead of local. Then if I want to switch from my iPad app to my iPhone on the go my project will be available.

As of now project files are stored in `On My iPad/Xogot`
It would be better in `iCloud Drive/Xogot`

**Comment by migueldeicaza** [comment]
Tracking this feature internally: https://github.com/xibbon/Xogot/issues/675

**Comment by endritdev1** [comment]
It would be great to have it with google drive as well, I mean all types of cloud storage platforms could be a huge goal. I mainly use google drive even though I use apple devices

**Comment by migueldeicaza** [comment]
Implemented on December 5th
