### ISSUE TITLE
Difficult to get Scene tree and folders back once turned off

### ISSUE THREAD

**Issue by iainx** [xibbon/XogotIssues#13]
1: Start a project, press the [<] button in the top left corner to access the sidebar
2: Click the two icons beside the magnifying glass in the bottom left corner to turn off the scene tree and the folders. The sidebar is now empty.
3: Click the two icons again to try to turn them back on. The scene tree and folders do not reappear
4: Click the magnifying glass to enter search mode
5: Click any of the three icons to exit search mode and the scene tree and folders reappear

**Comment by migueldeicaza** [comment]
Fixed
