### ISSUE TITLE
TileSet bottom panel is missing

### ISSUE THREAD

**Issue by switchCTRL** [xibbon/XogotIssues#14]
App: 1.0.1
OS: iPadOS 18.0.1
Device: iPad Pro (A2230)

If i select a tilemap with an associated tile set there is a tab missing on the bottom next to „tilemap“. 

![IMG_0753](https://github.com/user-attachments/assets/70232a45-8bfe-40d7-915b-00cbd597a2e4)

**Comment by migueldeicaza** [comment]
Question if you unselect and reselect the node, does it show up?

This seems to be a bug in Godot upstream

**Comment by migueldeicaza** [comment]
Fixed, please reopen if it still happens
