### ISSUE TITLE
Scroll offset wrong for welcome screen

### ISSUE THREAD

**Issue by switchCTRL** [xibbon/XogotIssues#15]
App: 1.0.1
OS: iPadOS 18.0.1
Device: iPad Pro (A2230)

It is not possible to scroll past a certain point on the welcome screen. There seems to be content but the scroll bar is already at the bottom. 

![IMG_0755](https://github.com/user-attachments/assets/c7608ecd-a5d6-40ac-9504-b2c96b0c53c7)
![IMG_0754](https://github.com/user-attachments/assets/7a2126d2-99fc-4eb2-ba6d-3727da695cf3)

**Comment by migueldeicaza** [comment]
Mhm, we are not able to reproduce this issue.

**Comment by migueldeicaza** [comment]
We reproduced it and fixed it.
