### ISSUE TITLE
Gamepads needs to be reconnected every time Xogot is launched.

### ISSUE THREAD

**Issue by jhaleit** [xibbon/XogotIssues#19]
If you connect a gamepad before launching Xogot it won’t work. You have to reconnect the gamepad after it’s open.

How to replicate:
1. Connect gamepad.
2. Launch Xogot.
3. Run your project.
4. Gamepad doesn’t work.
5. Turn gamepad off and back on.
6. It works!

If you close out of Xogot or if Xogot crashes you need to reconnect the gamepad again after it’s launched again.

**Comment by migueldeicaza** [comment]
Fixed in 1375
