### ISSUE TITLE
Lookup of code is not working and only display a blank screen 

### ISSUE THREAD

**Issue by andrekling** [xibbon/XogotIssues#36]
Clicking on a node to read it's documentation using the lookup function is not working, only displaying a blank text, no matter if using long press or reference guide.

**Comment by andrekling** [comment]
![IMG_0296](https://github.com/user-attachments/assets/516bffb0-16cd-49b2-a9d6-2a546fb9ece2)
![Uploading IMG_0297.png…]()

**Comment by andrekling** [comment]
![IMG_0296](https://github.com/user-attachments/assets/81949380-240f-45ff-a1c9-525df845efc7)

**Comment by migueldeicaza** [comment]
Thank you for raising this issue - this is definitely a regression, I am investigating.

**Comment by migueldeicaza** [comment]
Fixed, coming up.
