### ISSUE TITLE
Music pauses when launching project

### ISSUE THREAD

**Issue by celyk** [xibbon/XogotIssues#37]
Music and videos playing in picture in picture automatically pause when loading and running a project.

This can be annoying if you want to listen to music while developing. The solution would be add a setting to turn this off or better yet expose a way in GDScript to request the pause if desired.

**Comment by migueldeicaza** [comment]
Fixed, but I am tracking additional features, need to set/reset the state when playing a game, for users that have manually overwritten the iOS settings.
