### ISSUE TITLE
Can’t add physics layer in TileSet [Missing support for category .arrays]

### ISSUE THREAD

**Issue by mohfy** [xibbon/XogotIssues#38]
Tileset in my project:
 
<img width="320" alt="image" src="https://github.com/user-attachments/assets/29f79bf9-0678-4b33-9473-e53ede8ee998">

TileSet in example project:

<img width="320" alt="image" src="https://github.com/user-attachments/assets/c696c0d9-cae2-48ee-ba80-5c8e69f1c9b4">

**Comment by migueldeicaza** [comment]
I am not very familiar with the goal, what would the regular workflow do that is missing here?

**Comment by mohfy** [comment]
![image](https://github.com/user-attachments/assets/4a9c377a-8eb1-41f3-9368-22a047595e45)

I want this button for physics layers, it's missing when i create a new TileSet. But i can find this button in tilesets on example projects provided by Xogot.

**Comment by migueldeicaza** [comment]
Thank you, that explains it, will look into it.

**Comment by migueldeicaza** [comment]
Implemented, coming up in the next release.
