### ISSUE TITLE
Autoload file pickers do not offer all supported types

### ISSUE THREAD

**Issue by JosephHill** [xibbon/XogotIssues#42]
The file picker in Settings..Autoload..Add New Autoload is limited to the following file types:
- *.tscn
- *.scn
- *.res
- *.obj

Here is the complete list of file types available to select in Godot on the desktop:
- *.tres (*.tres)
- *.res (*.res)
- *.gd (*.gd)
- *.gdc (*.gdc)
- *.tscn (*.tscn)
- *.res (*.res)
- *.scn (*.scn)
- *.dae (*dae)
- *.obj (*.obj)
- *.escn (*.escn)
- *.fbx (*.fbx)
- *.gltf (*.gltf)
- *.glb (*.glb)

Additionally, the dialog has a Create Folder button that is probably not necessary since this dialog is for selecting an existing file.

### Report from Discord 
https://discord.com/channels/1305619658426155098/1307712485855592448/1311893326806650900

> When adding an autoload, only scenes show up when you try to select an existing file:

**Comment by migueldeicaza** [comment]
Fixed in 1a0192b70d4d47d9a3fdb83a0a2f35dcb2210767
