### ISSUE TITLE
Xodot fails to load dragonbones plugin

### ISSUE THREAD

**Issue by blurymind** [xibbon/XogotIssues#48]
I created a demo project here to test this

https://github.com/blurymind/godot4-dragonbones-demo-animations-and-slots

This works on desktop godot, but not on xodot.

![image](https://github.com/user-attachments/assets/ba389fbc-d984-49bf-8ae0-c7d94c2c8205)

**Comment by migueldeicaza** [comment]
This is expected, it is not possible to load dynamic native libraries on iOS, and the `libdraggonbones.ios.template_debug.xcframework` indicates the is the problem.

**Comment by blurymind** [comment]
Would it be possible to consider including the dragonbones runtime/extension in xodot itself?

Dragonbones editor still is the only free option for skeletal animation with mesh deformation.

Spine2d costs 400$ for the mesh deformation version

**Comment by migueldeicaza** [comment]
Yes, we are collecting the list of plugins that folks would like to bundle, feel free to fill up the original form again with that information.

**Comment by migueldeicaza** [comment]
Is it this one?

https://github.com/Daylily-Zeleen/Godot-DragonBones/tree/master

**Comment by blurymind** [comment]
> Is it this one?
> 
> https://github.com/Daylily-Zeleen/Godot-DragonBones/tree/master

Yes correct. There are other version of it, but this is the most supported one for newest godot 4 with the full implementation of the original dragonbones c++ runtime which it uses. To my knowledge it gives access to all db features.

Unlike the spine2d runtime license, the dragonbones license does not require an expensive 400$ purchase. And the animation editor is free to use https://dragonbones.github.io/en/index.html and can even be used under linux via wine or proton without any trouble. The editor has a mac version too.
The dragonbones animation editor is still light years ahead of godot's built in tools for animation, generating meshes, rigging and skin weights editing. 
If godot had better ux for that stuff and also as performant meshes, we wouldnt need to use spine2d or dragonbones. If you look at youtube, Dragonbones is a very popular way to animate assets for 2d games, it has a lot of support and tutorials, even though they kind of feature froze the editor

**Comment by migueldeicaza** [comment]
Let me convert this issue.
