### ISSUE TITLE
Rendering bug and a suggestion with how to fix it.

### ISSUE THREAD

**Issue by jhaleit** [xibbon/XogotIssues#50]
Mobile rendering is the only renderer working at the time of typing this so I'm guessing this is by design.   If I were to go on a PC or Mac and switch the renderer to `Forward+` or `Compatibility`, save it, and launch the project on Xogot I get a blank view port. 

Suggestions:

1. When opening a project check the renderer if it's set to `Mobile` and change if it's not.
2. When opening a project check the renderer if it's not set to `Mobile` and then display a popup warning about it with the option to change it.

**Comment by migueldeicaza** [comment]
I believe this is the `[rendering]`'s `renderer/rendering_method` value

**Comment by migueldeicaza** [comment]
Work in progress internally at: https://github.com/xibbon/Xogot/issues/886

**Comment by migueldeicaza** [comment]
Fixed, coming in the next release
